# LongGen/prompts/__init__.py
from .templates import (
    OUTLINE_GENERATION_TEMPLATE,
    QUERY_GENERATION_TEMPLATE,
    SECTION_WRITING_TEMPLATE,
    FILTER_TEMPLATE
)

__all__ = [
    'OUTLINE_GENERATION_TEMPLATE',
    'QUERY_GENERATION_TEMPLATE',
    'SECTION_WRITING_TEMPLATE',
    'FILTER_TEMPLATE'
]